version: '3'
services:
  app:
    container_name: full_app
    build: .  #path to Dockerfile
    ports: 
      - 3000:3000 
    restart: on-failure
    depends_on:
      - fullstack-postgres
    networks:
      - fullstack


  fullstack-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    env_file:
      - ./utils/.env
    ports:
      - '5432:5432'
    networks:
      - fullstack

volumes:
  api:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge
